### ISSUE TITLE
Site header text overlaps the logo

### ISSUE THREAD

**Issue by stestagg** [pythonjobs/jobs#38]
On iPhone, at least, the min-width has been lost so the text overlaps the logo

**Comment by lordmauve** [comment]
There's a CSS3 media query at the bottom of site.css that is supposed to
resize the font on smaller screens so that it doesn't overlap the logo. The
values might not be right for iPhone though - there's a bit of guesswork
involved. Or it may need another level of resizing for even smaller
(virtual) screens.

**Comment by salimfadhley** [comment]
The site is looking very bold right now - a little bit too bold. I think the latest style changes I pushed might be to blame.

**Comment by stestagg** [comment]
Fixed now
